# Generated by Django 2.0.4 on 2018-06-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(default='#', null=True, verbose_name='Repositorio'),
        ),
    ]
