# Generated by Django 2.0.4 on 2018-06-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180620_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=200, null=True, verbose_name='Lenguaje'),
        ),
    ]
