# Generated by Django 2.0.4 on 2018-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180619_1620'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='get_blogPost', to='blog.Category', verbose_name='Categorias'),
        ),
    ]
