# Generated by Django 2.0.4 on 2018-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subtítulo'),
        ),
    ]
