# Generated by Django 2.0.4 on 2018-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180619_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtítulo'),
        ),
    ]
